export enum TimelineEventType {
  CART_ITEM_ADDED = 'CART_ITEM_ADDED',
  CART_ITEM_UPDATED = 'CART_ITEM_UPDATED',
  CART_ITEM_REMOVED = 'CART_ITEM_REMOVED',
  PRICING_CALCULATED = 'PRICING_CALCULATED',
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
}

export enum TimelineEventSource {
  WEB = 'web',
  API = 'api',
  WORKER = 'worker',
}
